# Generated by Django 3.2.11 on 2022-03-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_alter_movie_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screening',
            options={'ordering': ['cinema__name', 'movie__title', 'date']},
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
